version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - resume-analyzer-network

  # Backend service
  backend:
    build: ./backend
    container_name: resume-analyzer-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017/
      - DB_NAME=resume_analyzer
      - DEBUG=True
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - resume-analyzer-network

  # Frontend service
  frontend:
    build: ./frontend
    container_name: resume-analyzer-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - resume-analyzer-network

volumes:
  mongodb_data:

networks:
  resume-analyzer-network:
    driver: bridge 